name: CloudHub Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code repo
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and deploy to cloudHUb
      run: mvn clean deploy -DmuleDeploy -DmuleVersion=4.4.0 --file pom.xml .maven/settings.xml
